<SP-11>: Created Repository level and pom updated
Viacheslav-Pavliuk/summer_prictice pull request #3
Opened 2021-06-17 14:18 UTC by Viacheslav-Pavliuk

- Created entities
- Created repositories
- Set uped flyway
- Generated migration
- Created tests for repositories

2021-06-18 08:24 UTC, metlaivan requested changes
Take into account.!!!!!!!!!!
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html
https://google.github.io/styleguide/javaguide.html#s5-naming

2021-06-18 08:24 UTC, metlaivan commented on src/main/java/com/summer_prictice/demo/ent/Warehouse.java
> +
No need an empty lines. Please use the formatting for all files.

2021-06-18 08:24 UTC, metlaivan commented on src/main/java/com/summer_prictice/demo/repos/ShipToRepo.java
> +public interface ShipToRepo extends CrudRepository<ShipTo,Long> {
Please use the same name for class names in repository level.

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/SummerPricticeApplicationTests.java
> +
no need empty lines.

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_ShipTo.java
> +public class Testing_ShipTo {
Use class name format

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_ShipTo.java
> +    @Test
please format the class

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_ShipTo.java
> +        LocalDate date_cr = LocalDate.of(2011,11,11);
field name must be in Java style

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_ShipTo.java
> +        Warehouse wh = WhR.findById(Long.valueOf("3")).get();
Long.valueOf("3") -> 3L

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_ShipTo.java
> +    private WarehouseRepo WhR;
Please use the full name field.

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_ShipTo.java
> +        assertEquals(sTR.findById(Long.valueOf("4")).get().getCreatedat(),date_cr);
Why 4.

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_ShipTo.java
> +        assertTrue(sTR.findById(Long.valueOf("4")).isPresent());
never execute.

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_Warehouse.java
> +        Warehouse WT=new Warehouse();
please use normal variable names.

2021-06-18 08:24 UTC, metlaivan commented on src/test/java/com/summer_prictice/demo/Testing_distributor.java
> +public class Testing_distributor {
format the code

2021-06-18 08:26 UTC, metlaivan commented
Please check the description of the task. Do you use all technologies from the list?

2021-06-22 07:57 UTC, metlaivan approved these changes

2021-06-22 07:57 UTC, metlaivan commented on pom.xml
> +            <plugin>
What do you do with that plugin?

2021-06-22 08:00 UTC, metlaivan commented
You should put the test in the same package as tested class.

2021-06-22 08:02 UTC, Viacheslav-Pavliuk commented on pom.xml
> +            <plugin>
This is an old edit, I forgot to delete this.

2021-06-22 18:01 UTC, merged